### ISSUE TITLE
case insensitive search

### ISSUE THREAD

**Issue by JTvD** [iBridges-for-iRODS/iBridges-GUI#269]
General question, when using the GUI we noticed the metadata searches are case sensitive. 
As people all have their own preferred way of entering data we get both 'Potato' and 'potato'.

The PRC has an option to query case insensitive:   session.irods_session.query(case_sensitive = False)
Is it possible to change the default implementation to this? 
Users can still look to the list for the objects/collections they want to download.

**Comment by chStaiger** [comment]
We can do that in the API.
